language: java

os:
  - windows
  - linux
  
 jobs:
 include:
    - stage: test
      script: .\src\test\java\com\swarm\graphql\query\TestRunner.java
    - # stage name not required, will continue to use `test`